development: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  database: jobhun_development
  collation: utf8mb4_general_ci
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  <<: *default
  database: jobhun_test

production:
  <<: *default
  database: jobhun_production

staging:
  <<: *default
  database: jobhun_staging
